name: ecommerce
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  jiffy: ^6.3.1
  #  Images
  cached_network_image: ^3.3.1
  #  Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.2.0
  #  Google Map
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.7.0
#    Firebase And Notification
  firebase_messaging: ^15.0.2
#  flutter_local_notifications: ^17.2.1+1
  cloud_firestore: ^5.0.2
  #  Local Data Cache
  shared_preferences: ^2.2.3
  #  Qrcode
  qr_flutter: ^4.1.0
  scan: ^1.6.0
  grouped_list: ^6.0.0
  url_launcher: ^6.3.0
  dropdown_search: ^5.0.6
  badges: ^3.1.2
  #  Icon
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  #  Google Auth
  google_sign_in: ^6.2.1
  device_preview: ^1.2.0
  responsive_builder: ^0.7.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.1.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.2
  uuid: ^4.2.2
  flutter_local_notifications: ^16.3.2
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
#
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
#
  location: ^6.0.0
  geocoding: ^3.0.0
  path: ^1.9.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  get: ^4.6.6
  flutter_otp_text_field: ^1.1.3+2
  recaptcha_enterprise_flutter: ^18.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - svg/facebook.svg
    - svg/google.svg
    - svg/twitter.svg
    - logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
